dist: xenial
language: python
python: 3.7
cache: pypi

install:
  - pip3 install coverage

script:
  - python3 -m pytest -vvv my_proj/
  - coverage run -m unittest discover

branches:
  only:
  - master

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
