dist: xenial
language: python
python: 3.7
cache: pypi

install:
  - pip install flake8 codecov pytest pytest-cov

script:
  - python -m flake8 my_proj/
  - python -m pytest -vvv my_proj/ --cov my_proj

after_success:
  - codecov

branches:
  only:
  - master
